export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const API_FAILURE = 'API_FAILURE';
export const SEAL_STATUS_SUCCESS = 'SEAL_STATUS_SUCCESS';
export const LIST_MOUNT_SUCCESS = 'LIST_MOUNT_SUCCESS';
export const GET_SECRET_SUCCESS = 'GET_SECRET_SUCCESS';
